### ISSUE TITLE
Sol doesn't compile on an ARM processor

### ISSUE THREAD

**Issue by lannonbr** [sol-lang/sol#1]
I try running build.sh on my Rasberry Pi and it fails to build properly. When compiling, gcc is complaining that there are two size_t types (one defined as part of gcc, and the one in dsl.h).

**Comment by Grissess** [comment]
The one in dsl is a bug workaround for a particular build environment (probably my laptop) and should have never been included in the source tree. Nonetheless, finding size_t proper across compilers has been tricky in practice; stdlib tends to have both it and ssize_t, which DSL requires to function properly.

You can delete the line and it should build (it did on my Pi, probably after the same calisthenics). I'll push a fix to DSL at my next opportunity.
