### ISSUE TITLE
Immutable Variables

### ISSUE THREAD

**Issue by lannonbr** [sol-lang/sol#17]
A very nice idea to come out of Functional Programming is the idea of immutability, where data is frozen and cant be changed after it is assigned. At this moment, I think we should add a keyword to say that a variable is immutable. does anyone have any ideas for such keyword?

**Comment by Grissess** [comment]
Maybe "immut" to counter Rust's "mut"?

**Comment by joemahmah** [comment]
I like "chain".

**Comment by Grissess** [comment]
whynotboth.jpg

**Comment by joemahmah** [comment]
yes

**Comment by lannonbr** [comment]
ruby has a freeze method, maybe something similar to freeze?

**Comment by Grissess** [comment]
whynotall.jpg

**Comment by lannonbr** [comment]
I am starting a branch called immute

**Comment by Grissess** [comment]
To be sure: this was going to be a per-object, not per-reference thing?

Per-object is pretty easy to do by introduction of a field to the `sol_object_t` structure, but then you'd need to check all the places where it could be mutated (e.g. list:insert, op add, tbang, etc.), which is nontrivial and finicky; per-reference would require a change to how the EX_REF/EX_ASSIGN expressions are evaluated in `sol_eval_inner` and, perhaps penultimately, how names get looked up in maps, which is not that hard if you think it through.

I'm nonetheless in support of either, or even both :P

**Comment by lannonbr** [comment]
Yea it will be per-object

**Comment by Grissess** [comment]
Have fun finding the places where objects are mutated, then :P 

This isn't a fast-and-hard list, nor is it authoritative, but you'll probably find mutator methods in
- _sol_f_tbang_, obviously
- Most of the _sol_f_list__ ops, like insert and map (but not copy or add--those return new objects)
- Most of the _sol_f_map__ ops, as above
- _sol_f_buffer_set_, though that's not the object--that's the underlying buffer.

If you'd like to make it hard on extension developers too (they'd have to deal with immutability), you can instead implement it right in the core methods for handling those structures--namely the _sol_map__ and _sol_list__ methods in `object.c`.

Good luck :D
