### ISSUE TITLE
Sol neovim plugin

### ISSUE THREAD

**Issue by lannonbr** [sol-lang/sol#18]
Syntax highlighting for the language for Neovim might be a simple thing to write since the plugin API in Neovim is much better than VimL. Is anyone interested in writing it?

**Comment by Grissess** [comment]
I have a half-implemented VimL plugin stolen from vim74's lua.vim (with everything renamed with %s), if you'd like a base or stand-in for a bit :P

**Comment by lannonbr** [comment]
Sure, send it over and I can start working on it over break.

**Comment by Grissess** [comment]
I never said it was good (it still has a lot of Lua-ese in it), but here's my local copy :D
[sol.txt](https://github.com/sol-lang/sol/files/43071/sol.txt)
(Note that it's really a ".vim" file, but Github didn't like that; drop it into your vim/vim74/syntax or nvim/runtime/syntax :P)
