### ISSUE TITLE
Initialization file

### ISSUE THREAD

**Issue by Grissess** [sol-lang/sol#20]
Dynamic programming languages that I am well aware of (particularly Python) have a set of files that are run initially before beginning to interpret code. In doing so, this allows user to customize the initial environment more easily than doing so in, e.g., `sol_state_init`. It is in such a way that I would preferentially implement the tools for a package manager (given that the runtime already supports enough basic functionality to begin this project).

Any feelings on what and where these files should be?

**Comment by lannonbr** [comment]
Either /opt/sol/ or ~/.config/sol/
