### ISSUE TITLE
Live Interpretation in the C Interpreter

### ISSUE THREAD

**Issue by joemahmah** [sol-lang/sol#22]
Currently, the only means to interpret sol live is to use the interpreter written in sol.

When using something written in sol, stability appears to go down the drain. This becomes much more evident when using the !!! operator...

**Comment by Grissess** [comment]
This is NOTABUG: in theory, the language should be stable enough to self-interpret. If there is an issue with that, excising that issue to a single Sol source file which can be run outside of the interpreter is standard practice, and by all means desirable. Having the interpreter additionally be Sol-based furthermore permits usage of Sol-hosted debugging utilities, like `solid`.

Bugs in the interpreter itself should be reported and fixed as always, but bugs shouldn't be raised against the interpreter for language faults. Please report either, of course!
