### ISSUE TITLE
Add gradual type system

### ISSUE THREAD

**Issue by emberian** [sol-lang/sol#25]
Some references: http://www.typescriptlang.org/

https://www.cs.colorado.edu/~siek/pubs/pubs/2006/siek06:_gradual.pdf

**Comment by emberian** [comment]
http://www.cs.cmu.edu/~aldrich/FOOL/fool08/siek-slides.pdf

**Comment by Grissess** [comment]
I chose the Python 3 solution; annotations on parameters and functions themselves are supported through the .annos field of function objects, populated when they are generated from a FuncDecl. (They are legal in all forms of FuncDecl, including `lambda`.) See [tests/lang_anno.sol
](tests/lang_anno.sol) for a working example of typechecking.

Comment if these features are not sufficient to implement this system; I'll reopen the issue.
